language: c
before_install:
  - git clone https://github.com/sstephenson/bats bats
  - sudo apt-get install -q -y libgmp3c2

install:
  - cd bats && sudo ./install.sh /usr/local && cd -

script:
  - hsvm install 7.6.3
  - bats test/

env:
  - PATH="${TRAVIS_BUILD_DIR}/bin:$PATH"
